[build]
  base = "packages/algolia-netlify"
  command = "NODE_ENV=production yarn build"
  functions = "build/functions"

[build.environment]
  NODE_VERSION = "14"
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"

[template.environment]
  ALGOLIA_ACTIVE = "TRUE or FALSE. Set to TRUE to trigger indexing."
  ALGOLIA_APP_ID = "Algolia Application ID"
  ALGOLIA_API_KEY = "An Algolia Admin API Key or a generated one"
  ALGOLIA_INDEX = "Name of the Algolia index"
